# Generated by Django 2.1.1 on 2018-09-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(db_index=True, help_text='A name to identify this template', max_length=100, unique=True),
        ),
    ]
